### ISSUE TITLE
How should I modify loss?

### ISSUE THREAD

**Issue by zhangzh666123** [fundwotsai2001/AP-adapter#3]
(base) root@autodl-container-fa34479161-7d556751:~/sd# bash trainNew.sh 
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
08/21/2024 21:52:53 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

Loading pipeline components...:   0%|                                                                                                                                                                                                                                                                 | 0/11 [00:00<?, ?it/s]Loaded vocoder as SpeechT5HifiGan from `vocoder` subfolder of ckpt.
Loading pipeline components...:   9%|██████████████████████▋                                                                                                                                                                                                                                  | 1/11 [00:00<00:05,  1.86it/s]Loaded unet as AudioLDM2UNet2DConditionModel from `unet` subfolder of ckpt.
Loading pipeline components...:  18%|█████████████████████████████████████████████▎                                                                                                                                                                                                           | 2/11 [00:03<00:16,  1.84s/it]Loaded scheduler as DDIMScheduler from `scheduler` subfolder of ckpt.
Loaded feature_extractor as ClapFeatureExtractor from `feature_extractor` subfolder of ckpt.
Loaded text_encoder as ClapModel from `text_encoder` subfolder of ckpt.
Loading pipeline components...:  45%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                                       | 5/11 [00:04<00:05,  1.13it/s]Loaded tokenizer as RobertaTokenizerFast from `tokenizer` subfolder of ckpt.
Loaded projection_model as AudioLDM2ProjectionModel from `projection_model` subfolder of ckpt.
Loaded vae as AutoencoderKL from `vae` subfolder of ckpt.
Loading pipeline components...:  73%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                    | 8/11 [00:05<00:01,  2.07it/s]Loaded text_encoder_2 as T5EncoderModel from `text_encoder_2` subfolder of ckpt.
Loading pipeline components...:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                             | 9/11 [00:07<00:01,  1.30it/s]Loaded language_model as GPT2Model from `language_model` subfolder of ckpt.
Loading pipeline components...:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 10/11 [00:07<00:00,  1.30it/s]Loaded tokenizer_2 as T5TokenizerFast from `tokenizer_2` subfolder of ckpt.
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:07<00:00,  1.40it/s]use apadapter

wandb: Tracking run with wandb version 0.17.7
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
08/21/2024 21:53:12 - INFO - __main__ - ***** Running training *****
08/21/2024 21:53:12 - INFO - __main__ -   Num examples = 2
08/21/2024 21:53:12 - INFO - __main__ -   Num Epochs = 500000
08/21/2024 21:53:12 - INFO - __main__ -   Instantaneous batch size per device = 7
08/21/2024 21:53:12 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 28
08/21/2024 21:53:12 - INFO - __main__ -   Gradient Accumulation steps = 4
08/21/2024 21:53:12 - INFO - __main__ -   Total optimization steps = 1000000
Current process is using device: 0
Steps:   0%|                                                                                                                                                                                                                                                                                     | 0/1000000 [00:00<?, ?it/s]/root/miniconda3/lib/python3.8/site-packages/audioldm/audio/stft.py:42: FutureWarning: Pass size=1024 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  fft_window = pad_center(fft_window, filter_length)
/root/miniconda3/lib/python3.8/site-packages/audioldm/audio/stft.py:145: FutureWarning: Pass sr=16000, n_fft=1024, n_mels=64, fmin=0, fmax=8000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel_basis = librosa_mel_fn(
/root/miniconda3/lib/python3.8/site-packages/audioldm/audio/stft.py:42: FutureWarning: Pass size=1024 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  fft_window = pad_center(fft_window, filter_length)
/root/miniconda3/lib/python3.8/site-packages/audioldm/audio/stft.py:145: FutureWarning: Pass sr=16000, n_fft=1024, n_mels=64, fmin=0, fmax=8000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel_basis = librosa_mel_fn(
**Traceback (most recent call last):
  File "train_apadapter_v2.py", line 1053, in <module>
    main()
  File "train_apadapter_v2.py", line 963, in main
    accelerator.backward(loss)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/accelerator.py", line 2159, in backward
    loss.backward(**kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: invalid argument
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.**

-------------------------------------------------------------------------------------------------------

When I comment out the line 
`accelerator.backward(loss)`
the model can train normally. How should I modify it?

**Comment by fundwotsai2001** [comment]
Sorry, I am not sure about this, but maybe try using python=3.11?

**Comment by zhangzh666123** [comment]
> Sorry, I am not sure about this, but maybe try using python=3.11?

yes, after I changed it to 3.11 (and also modified the corresponding PyTorch version), the error disappeared."
